application: ai-demo
environment: dev

terraform:
  variables:
    datadog_api_key:
      secret_id: /platform/dev/datadog
      json_key: api_key
      tf_var: datadog_api_key

datadog:
  enabled: true
  api_key:
    secret_id: /platform/dev/datadog
    json_key: api_key

sonarqube:
  enabled: true
  token:
    secret_id: /platform/dev/sonarqube
    json_key: token
